### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by VincentGardeux** [natsuhiko/PHM#3]
Hello, the current code is not compiling:

```
PHM-0.2/src/bayeslm.c:44: undefined reference to `clearAs0'
PHM-0.2/src/util_bayeslm.c:600: undefined reference to `sumTo1'
PHM-0.2/src/util_bayeslm.c:575: undefined reference to `wsoftmax'
```

and more...

**Comment by natsuhiko** [comment]
Hi,

I fixed the problem in the Makefile. 

Could you download and recompile it again?

Best regards,
Natsuhiko

**Comment by VincentGardeux** [comment]
Yep thanks it works now

Regards
