### ISSUE TITLE
pmr.gz output clarification

### ISSUE THREAD

**Issue by arushiv** [natsuhiko/PHM#5]
Hello,

I wanted to clarify what the columns are in the pmr.gz outputs from PHM and how to calculate the probability of a 'master regulator' for a peak. I assumed that each row in this file would correspond to one peak, and provide the peak id, P(MR | peak is a QTL), expected number of upstream/downstream peaks etc. However, I see that there can be multiple rows in the output with the same peak id in the 4th column (MAP peak id) of the pmr.gz output. Does this mean that the pmr.gz file has one row for each causal peak pair? If so, which is the 'target' peak? How would one calculate PMR from these outputs?

Thanks,

**Comment by natsuhiko** [comment]
Hi Arushi,

Thanks for using PHM.

Each row of 'pmr.gz' corresponds to each peak you annotated with log PMR value (1st column). So if you want to know peaks with PMR>0.9 (precisely speaking P(MR|the peak is a QTL)>0.9), the following awk command gives you the list of peak IDs:

% zcat pmr.gz | awk 'exp($1)>0.9{print NR}'

The 4th column tells you which peak is the parent peak for that peak with the posterior probability (5th column). For example, if you have the following regulatory structure (Peak1 regulates Peak2 & Peak3 and then Peak3 regulates Peak4):

Peak1 
    |--Peak2
    |--Peak3
            |--Peak4

pmr.gz should be like:

0.0 3 0 2 0.0
-20 0 1 1 1.0
-20 1 1 1 1.0
-20 0 1 3 1.0

The reason why you see the same peak ID on the 4th column is that the repeated peak ID is likely to be the master regulatory peak in the region (in the above example, you see Peak1 twice on the 4th column). In this way, you can construct the tree structure with the column 4 and 5.

Best regards,
Natsuhiko

**Comment by arushiv** [comment]
Hi Natsuhiko,

PHM is really neat and quite useful for us! Thanks for the quick reply, all makes sense now.

Best,
Arushi
